### ISSUE TITLE
Store MailChimp tracking parameters and pass to API requests

### ISSUE THREAD

**Issue by ruscoe** [thinkshout/mailchimp_ecommerce#9]
Tracking parameters will be received as URL parameters when a user enters the site via a link from a MailChimp campaign email.

The tracking parameter names are:
- mc_cid
  Internal MailChimp campaign ID.
- mc_eid
  Unique, MailChimp-generated ID for the list subscriber.
- [x] Store the tracking parameters in the user's session
- [x] Overwrite the stored tracking parameters if received again
- [x] Pass tracking parameters to all API calls that support them
- [x] Ensure that a campaign ID is a valid, active campaign before saving an order/customer with the campaign

**Comment by Greg-Boggs** [comment]
example.com/?mc_cid=019ae1bda8&mc_eid=110b0f9d85

**Comment by Greg-Boggs** [comment]
If you try to save an order or cart with an invalid campaign ID you get an error. So, before we save a campaign ID we need to confirm that the given ID is an active, valid campaign.

**Comment by taz77** [comment]
This gives me an idea. Many people use Affiliate NG and/or Commerce Affiliate with Drupal 7.

**Comment by Greg-Boggs** [comment]
We'll need to provide a hook so that people can alter the information sent to mailchimp so they can additional custom data. Or, we can just encourage people to expand the code. :)

**Comment by taz77** [comment]
Yeah I am thinking about a helper module that provides some glue between mailchimp main module, ecommerce, and the affiliate modules. The idea sparked in my head reading this issue.
